import os
import sys
import csv
from time import sleep
from datetime import date

import requests

from bbc6_scraper import STATIONS, scrape_playlist
from deezer_lookup import search_deezer_track

from google.oauth2.credentials import Credentials
from google.auth.transport.requests import Request
from googleapiclient.discovery import build


# ============================================================
# YOUTUBE AUTHENTICATION
# ============================================================

YOUTUBE_SCOPES = [
    "https://www.googleapis.com/auth/youtube"
]


def get_youtube_service():
    """Authenticate with YouTube using the GitHub Actions secrets."""

    credentials = Credentials(
        token=None,
        refresh_token=os.environ["YOUTUBE_REFRESH_TOKEN"],
        token_uri="https://oauth2.googleapis.com/token",
        client_id=os.environ["YOUTUBE_CLIENT_ID"],
        client_secret=os.environ["YOUTUBE_CLIENT_SECRET"],
        scopes=YOUTUBE_SCOPES,
    )

    credentials.refresh(Request())

    return build(
        "youtube",
        "v3",
        credentials=credentials
    )


# ============================================================
# YOUTUBE PLAYLIST FUNCTIONS
# ============================================================

def get_or_create_playlist(youtube, station_name):
    """
    Find a YouTube playlist matching the station name.
    If it doesn't exist, create it.
    """

    playlist_title = station_name

    print(f"Checking YouTube playlist: {playlist_title}")

    # Get all playlists belonging to the authenticated account.
    request = youtube.playlists().list(
        part="snippet",
        mine=True,
        maxResults=50
    )

    while request:
        response = request.execute()

        for playlist in response.get("items", []):
            title = playlist["snippet"]["title"]

            if title.lower() == playlist_title.lower():
                playlist_id = playlist["id"]

                print(
                    f" -> Found existing YouTube playlist: "
                    f"{title} ({playlist_id})"
                )

                return playlist_id

        request = youtube.playlists().list_next(
            request,
            response
        )

    # Playlist doesn't exist, so create it.
    print(f" -> Creating YouTube playlist: {playlist_title}")

    playlist_body = {
        "snippet": {
            "title": playlist_title,
            "description": (
                f"Songs played on {station_name}, "
                "automatically generated by the radio scraper."
            )
        },
        "status": {
            "privacyStatus": "public"
        }
    }

    response = youtube.playlists().insert(
        part="snippet,status",
        body=playlist_body
    ).execute()

    playlist_id = response["id"]

    print(
        f" -> Created YouTube playlist: "
        f"{playlist_title} ({playlist_id})"
    )

    return playlist_id


def get_playlist_video_ids(youtube, playlist_id):
    """
    Get the YouTube video IDs already contained in a playlist.
    """

    video_ids = set()

    request = youtube.playlistItems().list(
        part="contentDetails",
        playlistId=playlist_id,
        maxResults=50
    )

    while request:
        response = request.execute()

        for item in response.get("items", []):
            video_id = item["contentDetails"]["videoId"]
            video_ids.add(video_id)

        request = youtube.playlistItems().list_next(
            request,
            response
        )

    return video_ids


def search_youtube_video(youtube, artist, title):
    """
    Search YouTube for a song and return the first video ID found.
    """

    query = f"{artist} {title}"

    print(f"    Searching YouTube: {query}")

    response = youtube.search().list(
        part="snippet",
        q=query,
        type="video",
        videoCategoryId="10",
        maxResults=1
    ).execute()

    items = response.get("items", [])

    if not items:
        print("    -> No YouTube result found")
        return None

    video_id = items[0]["id"]["videoId"]

    video_title = items[0]["snippet"]["title"]

    print(
        f"    -> YouTube result: {video_title} "
        f"(https://www.youtube.com/watch?v={video_id})"
    )

    return video_id


def add_video_to_playlist(youtube, playlist_id, video_id):
    """
    Add a YouTube video to a playlist.
    """

    body = {
        "snippet": {
            "playlistId": playlist_id,
            "resourceId": {
                "kind": "youtube#video",
                "videoId": video_id
            }
        }
    }

    youtube.playlistItems().insert(
        part="snippet",
        body=body
    ).execute()

    print(f"    -> Added video to playlist")


# ============================================================
# CSV FUNCTIONS
# ============================================================

OUTPUT_DIR = os.path.join(
    os.path.dirname(__file__),
    "output"
)

FIELDNAMES = [
    "date",
    "time",
    "artist",
    "title",
    "genre",
    "deezer_link"
]


def get_csv_path(station_name):
    """Build the CSV file path for a given station."""

    os.makedirs(OUTPUT_DIR, exist_ok=True)

    return os.path.join(
        OUTPUT_DIR,
        f"{station_name}.csv"
    )


def load_existing_keys(path):
    """Read existing rows from a station's CSV to avoid duplicates."""

    existing_keys = set()

    if not os.path.exists(path):
        return existing_keys

    with open(
        path,
        "r",
        encoding="utf-8",
        newline=""
    ) as f:

        reader = csv.DictReader(f)

        for row in reader:

            key = (
                f"{row.get('artist', '')}|"
                f"{row.get('title', '')}"
            ).lower().strip()

            existing_keys.add(key)

    return existing_keys


def append_track_to_csv(station_name, track):
    """
    Append a single track row to that station's CSV.

    Returns True if the track was newly added.
    Returns False if it already existed.
    """

    path = get_csv_path(station_name)

    key = (
        f"{track['artist']}|"
        f"{track['title']}"
    ).lower().strip()

    existing_keys = load_existing_keys(path)

    if key in existing_keys:
        return False

    file_exists = os.path.exists(path)

    with open(
        path,
        "a",
        encoding="utf-8",
        newline=""
    ) as f:

        writer = csv.DictWriter(
            f,
            fieldnames=FIELDNAMES
        )

        if not file_exists:
            writer.writeheader()

        writer.writerow({
            "date": date.today().isoformat(),
            "time": track.get("time", ""),
            "artist": track.get("artist", ""),
            "title": track.get("title", ""),
            "genre": track.get("genre", "Unknown"),
            "deezer_link": track.get("deezer_link", ""),
        })

    return True


# ============================================================
# STATION PROCESSING
# ============================================================

def process_station(station_name, url):
    """
    Scrape one station's playlist, enrich with Deezer info,
    write to CSV and add new songs to YouTube.
    """

    print(f"\n=== Processing {station_name} ===")

    log_path = os.path.join(
        OUTPUT_DIR,
        f"{station_name}_log.txt"
    )

    os.makedirs(
        OUTPUT_DIR,
        exist_ok=True
    )

    with open(
        log_path,
        "a",
        encoding="utf-8"
    ) as log:

        log.write(
            f"Script started (daily) for {station_name}\n"
        )

    # --------------------------------------------------------
    # Authenticate with YouTube
    # --------------------------------------------------------

    try:
        youtube = get_youtube_service()

        print(
            "Successfully authenticated with YouTube"
        )

    except Exception as e:

        print(
            f"ERROR: Could not authenticate with YouTube: {e}"
        )

        return []

    # --------------------------------------------------------
    # Get/create station playlist
    # --------------------------------------------------------

    try:

        playlist_id = get_or_create_playlist(
            youtube,
            station_name
        )

        print(
            f"YouTube playlist ID: {playlist_id}"
        )

        # Get videos already in the playlist.
        youtube_video_ids = get_playlist_video_ids(
            youtube,
            playlist_id
        )

        print(
            f"YouTube playlist currently contains "
            f"{len(youtube_video_ids)} videos"
        )

    except Exception as e:

        print(
            f"ERROR: Could not access/create YouTube playlist "
            f"for {station_name}: {e}"
        )

        return []

    # --------------------------------------------------------
    # Scrape station
    # --------------------------------------------------------

    try:

        songs = scrape_playlist(url)

    except Exception as e:

        print(
            f"Failed to scrape {station_name}: {e}"
        )

        return []

    print(
        f"Scraped {len(songs)} tracks from {station_name}"
    )

    enriched = []

    # --------------------------------------------------------
    # Process songs
    # --------------------------------------------------------

    for idx, song in enumerate(
        songs,
        start=1
    ):

        artist = song["artist"]
        title = song["title"]

        print(
            f"[{idx}/{len(songs)}] "
            f"({station_name}) "
            f"{artist} - {title}"
        )

        # ----------------------------------------------------
        # Check CSV
        # ----------------------------------------------------

        csv_key = (
            f"{artist}|{title}"
        ).lower().strip()

        csv_path = get_csv_path(
            station_name
        )

        existing_keys = load_existing_keys(
            csv_path
        )

        already_in_csv = (
            csv_key in existing_keys
        )

        if already_in_csv:

            print(
                " -> Already exists in CSV"
            )

            # We don't need to process old tracks again.
            continue

        # ----------------------------------------------------
        # Deezer lookup
        # ----------------------------------------------------

        print(
            f" -> Searching Deezer: "
            f"{artist} - {title}"
        )

        deezer_info = search_deezer_track(
            artist,
            title
        )

        if deezer_info is None:

            print(
                " -> No Deezer match found"
            )

            continue

        song_with_deezer = {
            **song,
            "deezer_id": deezer_info["id"],
            "deezer_link": deezer_info["link"],
            "deezer_title": deezer_info["title"],
            "deezer_artist": deezer_info["artist"],
            "genre": deezer_info.get(
                "genre",
                "Unknown"
            ),
        }

        enriched.append(
            song_with_deezer
        )

        # ----------------------------------------------------
        # Add to CSV
        # ----------------------------------------------------

        added_to_csv = append_track_to_csv(
            station_name,
            song_with_deezer
        )

        if added_to_csv:

            print(
                f" -> Added to CSV: "
                f"{artist} - {title}"
            )

        # ----------------------------------------------------
        # Search YouTube
        # ----------------------------------------------------

        video_id = search_youtube_video(
            youtube,
            deezer_info["artist"],
            deezer_info["title"]
        )

        if video_id is None:

            print(
                " -> Could not find song on YouTube"
            )

            continue

        # ----------------------------------------------------
        # Check whether YouTube video is already in playlist
        # ----------------------------------------------------

        if video_id in youtube_video_ids:

            print(
                " -> Video is already in YouTube playlist"
            )

            continue

        # ----------------------------------------------------
        # Add to YouTube playlist
        # ----------------------------------------------------

        try:

            add_video_to_playlist(
                youtube,
                playlist_id,
                video_id
            )

            youtube_video_ids.add(
                video_id
            )

        except Exception as e:

            print(
                f" -> ERROR adding video to playlist: {e}"
            )

        sleep(0.3)

    # --------------------------------------------------------
    # Summary
    # --------------------------------------------------------

    print(
        f"\nSuccessfully matched "
        f"{len(enriched)} new tracks on Deezer "
        f"for {station_name}"
    )

    for track in enriched[:10]:

        print(
            f"{track['time']} - "
            f"{track['artist']} - "
            f"{track['title']} "
            f"({track.get('genre', 'Unknown')}) "
            f"-> {track['deezer_link']}"
        )

    with open(
        log_path,
        "a",
        encoding="utf-8"
    ) as log:

        log.write(
            f"Script finished (daily) for "
            f"{station_name}. "
            f"Matched {len(enriched)} tracks.\n"
        )

    return enriched


# ============================================================
# MAIN
# ============================================================

def run_daily():
    """
    Loop through every station in STATIONS
    and process each one separately.
    """

    for station_name, url in STATIONS.items():

        process_station(
            station_name,
            url
        )


if __name__ == "__main__":

    # Optionally run a single station:
    # python main.py bbc6

    if (
        len(sys.argv) > 1
        and sys.argv[1] in STATIONS
    ):

        process_station(
            sys.argv[1],
            STATIONS[sys.argv[1]]
        )

    else:

        run_daily()
