import os
import csv
import sys
from time import sleep

from google.oauth2.credentials import Credentials
from google.auth.transport.requests import Request
from googleapiclient.discovery import build


YOUTUBE_SCOPES = [
    "https://www.googleapis.com/auth/youtube"
]

OUTPUT_DIR = "output"


# ============================================================
# YOUTUBE AUTHENTICATION
# ============================================================

def get_youtube_service():
    """Authenticate with YouTube using GitHub Secrets."""

    credentials = Credentials(
        token=None,
        refresh_token=os.environ["YOUTUBE_REFRESH_TOKEN"],
        token_uri="https://oauth2.googleapis.com/token",
        client_id=os.environ["YOUTUBE_CLIENT_ID"],
        client_secret=os.environ["YOUTUBE_CLIENT_SECRET"],
        scopes=YOUTUBE_SCOPES,
    )

    credentials.refresh(Request())

    return build(
        "youtube",
        "v3",
        credentials=credentials
    )


# ============================================================
# PLAYLIST FUNCTIONS
# ============================================================

def get_or_create_playlist(youtube, station_name):
    """
    Find a YouTube playlist matching the station name.

    Returns:
        playlist_id, playlist_was_created
    """

    playlist_title = station_name

    print(f"Checking playlist: {playlist_title}")

    request = youtube.playlists().list(
        part="snippet",
        mine=True,
        maxResults=50
    )

    while request:

        response = request.execute()

        for playlist in response.get("items", []):

            title = playlist["snippet"]["title"]

            if title.lower() == playlist_title.lower():

                playlist_id = playlist["id"]

                print(
                    f" -> Found existing playlist: "
                    f"{title} ({playlist_id})"
                )

                return playlist_id, False

        request = youtube.playlists().list_next(
            request,
            response
        )

    # --------------------------------------------------------
    # Playlist does not exist - create it
    # --------------------------------------------------------

    print(
        f" -> Creating playlist: {playlist_title}"
    )

    playlist_body = {
        "snippet": {
            "title": playlist_title,
            "description": (
                f"Songs played on {station_name}, "
                "automatically generated by the radio scraper."
            )
        },
        "status": {
            "privacyStatus": "public"
        }
    }

    response = youtube.playlists().insert(
        part="snippet,status",
        body=playlist_body
    ).execute()

    playlist_id = response["id"]

    print(
        f" -> Created playlist: "
        f"{playlist_title} ({playlist_id})"
    )

    return playlist_id, True


def get_playlist_video_ids(youtube, playlist_id):
    """Get all video IDs currently in a playlist."""

    video_ids = set()

    request = youtube.playlistItems().list(
        part="contentDetails",
        playlistId=playlist_id,
        maxResults=50
    )

    while request:

        response = request.execute()

        for item in response.get("items", []):

            video_ids.add(
                item["contentDetails"]["videoId"]
            )

        request = youtube.playlistItems().list_next(
            request,
            response
        )

    return video_ids


def search_youtube_video(youtube, artist, title):
    """Search YouTube for a song."""

    query = f"{artist} {title}"

    print(
        f"  Searching YouTube: {query}"
    )

    response = youtube.search().list(
        part="snippet",
        q=query,
        type="video",
        videoCategoryId="10",
        maxResults=1
    ).execute()

    items = response.get("items", [])

    if not items:

        print(
            "  -> No YouTube result found"
        )

        return None

    video_id = items[0]["id"]["videoId"]

    video_title = items[0]["snippet"]["title"]

    print(
        f"  -> Found: {video_title}"
    )

    return video_id


def add_video_to_playlist(
    youtube,
    playlist_id,
    video_id
):
    """Add a video to a YouTube playlist."""

    body = {
        "snippet": {
            "playlistId": playlist_id,
            "resourceId": {
                "kind": "youtube#video",
                "videoId": video_id
            }
        }
    }

    youtube.playlistItems().insert(
        part="snippet",
        body=body
    ).execute()


# ============================================================
# CSV FUNCTIONS
# ============================================================

def load_csv(station_name):
    """Load all songs from a station CSV."""

    path = os.path.join(
        OUTPUT_DIR,
        f"{station_name}.csv"
    )

    if not os.path.exists(path):

        print(
            f"CSV not found: {path}"
        )

        return []

    with open(
        path,
        "r",
        encoding="utf-8",
        newline=""
    ) as f:

        return list(
            csv.DictReader(f)
        )


# ============================================================
# POPULATE PLAYLIST
# ============================================================

def populate_station(
    youtube,
    station_name,
    start=0,
    limit=None
):
    """Populate one station's YouTube playlist."""

    print()
    print("=" * 60)
    print(f"POPULATING: {station_name}")
    print("=" * 60)

    # --------------------------------------------------------
    # Load CSV
    # --------------------------------------------------------

    songs = load_csv(station_name)

    if not songs:

        print(
            "No songs found in CSV."
        )

        return

    songs = songs[start:]
    
    if limit:
        songs = songs[:limit]

    print(
        f"Songs to process: {len(songs)}"
    )

    # --------------------------------------------------------
    # Get or create playlist
    # --------------------------------------------------------

    playlist_id, playlist_was_created = (
        get_or_create_playlist(
            youtube,
            station_name
        )
    )

    # --------------------------------------------------------
    # Get existing videos
    # --------------------------------------------------------

    if playlist_was_created:

        # We just created it, therefore it is empty.
        existing_video_ids = set()

        print(
            "Playlist was just created, so it is empty."
        )

    else:

        existing_video_ids = (
            get_playlist_video_ids(
                youtube,
                playlist_id
            )
        )

        print(
            f"Playlist already contains "
            f"{len(existing_video_ids)} videos"
        )

    # --------------------------------------------------------
    # Process songs
    # --------------------------------------------------------

    added = 0
    skipped = 0
    failed = 0

    for index, song in enumerate(
        songs,
        start=1
    ):

        artist = song.get(
            "artist",
            ""
        ).strip()

        title = song.get(
            "title",
            ""
        ).strip()

        if not artist or not title:

            print(
                f"[{index}/{len(songs)}] "
                "Skipping empty artist/title"
            )

            continue

        print()
        print(
            f"[{index}/{len(songs)}] "
            f"{artist} - {title}"
        )

        # ----------------------------------------------------
        # Search YouTube
        # ----------------------------------------------------

        try:

            video_id = search_youtube_video(
                youtube,
                artist,
                title
            )

        except Exception as e:

            print(
                f"  -> YouTube search failed: {e}"
            )

            failed += 1
            continue

        if not video_id:

            failed += 1
            continue

        # ----------------------------------------------------
        # Check playlist
        # ----------------------------------------------------

        if video_id in existing_video_ids:

            print(
                "  -> Already in playlist"
            )

            skipped += 1
            continue

        # ----------------------------------------------------
        # Add video
        # ----------------------------------------------------

        try:

            add_video_to_playlist(
                youtube,
                playlist_id,
                video_id
            )

            existing_video_ids.add(
                video_id
            )

            added += 1

            print(
                "  -> ADDED to playlist"
            )

        except Exception as e:

            print(
                f"  -> Failed to add video: {e}"
            )

            failed += 1

        sleep(0.3)

    # --------------------------------------------------------
    # Summary
    # --------------------------------------------------------

    print()
    print("=" * 60)
    print(f"FINISHED: {station_name}")
    print("=" * 60)

    print(
        f"Added: {added}"
    )

    print(
        f"Already present: {skipped}"
    )

    print(
        f"Failed: {failed}"
    )


# ============================================================
# MAIN
# ============================================================

def main():

    # --------------------------------------------------------
    # Read GitHub Action inputs
    # --------------------------------------------------------

    station = sys.argv[1] if len(sys.argv) > 1 else "bbc6"
    start = int(sys.argv[2]) if len(sys.argv) > 2 else 0
    limit = int(sys.argv[3]) if len(sys.argv) > 3 else 5

    print(f"Station: {station}")
    print(f"Starting row: {start}")
    print(f"Songs to process: {limit}")

    # --------------------------------------------------------
    # Authenticate
    # --------------------------------------------------------

    youtube = get_youtube_service()

    print(
        "Successfully authenticated with YouTube."
    )

    # --------------------------------------------------------
    # Populate
    # --------------------------------------------------------

    populate_station(
        youtube,
        station,
        start=start,
        limit=limit
    )


if __name__ == "__main__":
    main()
