import os
import csv
import sys
from time import sleep

from google.oauth2.credentials import Credentials
from google.auth.transport.requests import Request
from googleapiclient.discovery import build


YOUTUBE_SCOPES = [
    "https://www.googleapis.com/auth/youtube"
]

OUTPUT_DIR = "output"


def get_youtube_service():
    """Authenticate with YouTube using GitHub Secrets."""

    credentials = Credentials(
        token=None,
        refresh_token=os.environ["YOUTUBE_REFRESH_TOKEN"],
        token_uri="https://oauth2.googleapis.com/token",
        client_id=os.environ["YOUTUBE_CLIENT_ID"],
        client_secret=os.environ["YOUTUBE_CLIENT_SECRET"],
        scopes=YOUTUBE_SCOPES,
    )

    credentials.refresh(Request())

    return build(
        "youtube",
        "v3",
        credentials=credentials
    )


def get_or_create_playlist(youtube, station_name):
    """Find the station playlist or create it."""

    print(f"\nChecking playlist: {station_name}")

    request = youtube.playlists().list(
        part="snippet",
        mine=True,
        maxResults=50
    )

    while request:
        response = request.execute()

        for playlist in response.get("items", []):
            title = playlist["snippet"]["title"]

            if title.lower() == station_name.lower():
                print(
                    f"Found playlist: {title} "
                    f"({playlist['id']})"
                )
                return playlist["id"]

        request = youtube.playlists().list_next(
            request,
            response
        )

    print(f"Creating playlist: {station_name}")

    body = {
        "snippet": {
            "title": station_name,
            "description": (
                f"Songs played on {station_name}, "
                "automatically generated by the radio scraper."
            )
        },
        "status": {
            "privacyStatus": "public"
        }
    }

    response = youtube.playlists().insert(
        part="snippet,status",
        body=body
    ).execute()

    playlist_id = response["id"]

    print(
        f"Created playlist: {station_name} "
        f"({playlist_id})"
    )

    return playlist_id


def get_playlist_video_ids(youtube, playlist_id):
    """Get all video IDs currently in a playlist."""

    video_ids = set()

    request = youtube.playlistItems().list(
        part="contentDetails",
        playlistId=playlist_id,
        maxResults=50
    )

    while request:
        response = request.execute()

        for item in response.get("items", []):
            video_ids.add(
                item["contentDetails"]["videoId"]
            )

        request = youtube.playlistItems().list_next(
            request,
            response
        )

    return video_ids


def search_youtube_video(youtube, artist, title):
    """Search YouTube for a song."""

    query = f"{artist} {title}"

    print(f"  Searching YouTube: {query}")

    response = youtube.search().list(
        part="snippet",
        q=query,
        type="video",
        videoCategoryId="10",
        maxResults=1
    ).execute()

    items = response.get("items", [])

    if not items:
        print("  -> No result found")
        return None

    video_id = items[0]["id"]["videoId"]

    video_title = items[0]["snippet"]["title"]

    print(
        f"  -> Found: {video_title}"
    )

    return video_id


def add_video_to_playlist(
    youtube,
    playlist_id,
    video_id
):
    """Add a video to a playlist."""

    body = {
        "snippet": {
            "playlistId": playlist_id,
            "resourceId": {
                "kind": "youtube#video",
                "videoId": video_id
            }
        }
    }

    youtube.playlistItems().insert(
        part="snippet",
        body=body
    ).execute()


def load_csv(station_name):
    """Load all songs from a station CSV."""

    path = os.path.join(
        OUTPUT_DIR,
        f"{station_name}.csv"
    )

    if not os.path.exists(path):
        print(f"CSV not found: {path}")
        return []

    with open(
        path,
        "r",
        encoding="utf-8",
        newline=""
    ) as f:

        return list(csv.DictReader(f))


def populate_station(
    youtube,
    station_name,
    limit=None
):
    """Populate one station's playlist."""

    print()
    print("=" * 60)
    print(f"POPULATING: {station_name}")
    print("=" * 60)

    songs = load_csv(station_name)

    if not songs:
        print("No songs found.")
        return

    if limit:
        songs = songs[:limit]

    print(
        f"Songs to process: {len(songs)}"
    )

    playlist_id, playlist_was_created = get_or_create_playlist(
    youtube,
    station_name
)

if playlist_was_created:
    # We just created the playlist, so it is empty.
    existing_video_ids = set()

    print(
        "Playlist was just created, so it is empty."
    )

else:
    # Existing playlist - check which videos are already there.
    existing_video_ids = get_playlist_video_ids(
        youtube,
        playlist_id
    )

    print(
        f"Playlist already contains "
        f"{len(existing_video_ids)} videos"
    )

    added = 0
    skipped = 0
    failed = 0

    for index, song in enumerate(
        songs,
        start=1
    ):

        artist = song.get(
            "artist",
            ""
        ).strip()

        title = song.get(
            "title",
            ""
        ).strip()

        if not artist or not title:
            continue

        print()
        print(
            f"[{index}/{len(songs)}] "
            f"{artist} - {title}"
        )

        try:

            video_id = search_youtube_video(
                youtube,
                artist,
                title
            )

            if not video_id:
                failed += 1
                continue

            if video_id in existing_video_ids:

                print(
                    "  -> Already in playlist"
                )

                skipped += 1
                continue

            add_video_to_playlist(
                youtube,
                playlist_id,
                video_id
            )

            existing_video_ids.add(
                video_id
            )

            added += 1

            print(
                "  -> ADDED to playlist"
            )

            sleep(0.3)

        except Exception as e:

            print(
                f"  -> ERROR: {e}"
            )

            failed += 1

    print()
    print(
        f"Finished {station_name}"
    )

    print(
        f"Added: {added}"
    )

    print(
        f"Already present: {skipped}"
    )

    print(
        f"Failed: {failed}"
    )


def main():

    youtube = get_youtube_service()

    print(
        "Successfully authenticated with YouTube."
    )

    # ---------------------------------------------------------
    # CHANGE THESE NAMES TO MATCH YOUR CSV FILES
    # ---------------------------------------------------------

    stations = [
        "bbc6",
        # "station2",
        # "station3",
        # "station4",
        # "station5",
    ]

    # Optional limit.
    #
    # Example:
    # LIMIT = 20
    #
    # This is useful for testing.
    #
    LIMIT = 5

    for station in stations:

        populate_station(
            youtube,
            station,
            limit=LIMIT
        )


if __name__ == "__main__":
    main()
